### ISSUE TITLE
Resizing follows mouse on Chrome

### ISSUE THREAD

**Issue by reverie** [davidjbradshaw/iframe-resizer#901]
**Describe the bug**
Our iframe resizes based on the position of the mouse in the parent window, rather than the content of the iframe. This only happens in Chrome. (Firefox and Safari work great and as intended). 

**To Reproduce**
Using iframe-resizer in normal configuration
From parent frame, move mouse on and out of iframe
Iframe resizes unexpectedly

**Expected behavior**
Iframe only resizes based on content, not outer window mouse position

**Screenshots**
https://user-images.githubusercontent.com/73446/104103661-5d001280-5271-11eb-9529-546df636c8bc.mp4

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest

**Comment by ImrozCinchy** [comment]
I am also following the same issue, any help will be appreciated.

**Comment by grokasm** [comment]
It appears the issue has been introduced in the latest release (4.3.0)
Reverting to 4.2.11 fixed the issue for me.

**Comment by davidjbradshaw** [comment]
@reverie I'm struggling to reproduce this. Can you please add the log output. Also do you see the same issue on the example?

**Comment by davidjbradshaw** [comment]
Also do you have version 4.3 in both the iframe and the parent page?

**Comment by davidjbradshaw** [comment]
Problem was if you had an older version on the parent page. Fixed in v4.3.1

**Comment by reverie** [comment]
@davidjbradshaw Right. Version mismatch, our mistake. Thanks for looking into this.

**Comment by davidjbradshaw** [comment]
In 4.3.1 it will disable the problem feature, if you don't have the at least 4.3.1 on the parent

**Comment by ImrozCinchy** [comment]
@davidjbradshaw So issue still persists for me when I move to version 4.3.1. It was all working before but when I installed iframe-resizer again it might have caused version mismatch but now it is just NOT working again even though if I go to back version when it was working.

**Comment by davidjbradshaw** [comment]
What version do you have in the iframe and on the parent page?

**Comment by ImrozCinchy** [comment]
In the iframe it is  4.3.1 and on parent 4.2.10. So even if I revert iframe to 4.2.10 which was working before it just doesn't work now. There is no change in parent.

**Comment by davidjbradshaw** [comment]
Not sure, if you put it back exactly how it was it should work. What does
the log say?

**Comment by ImrozCinchy** [comment]
I'll need to connect  with my other developer to get logs and further details. 
Meanwhile in Iframe when I revert to older version, in the package.json of iframe-resizer, I still get 
 "_resolved": "https://registry.npmjs.org/iframe-resizer/-/iframe-resizer-4.3.1.tgz",
 
 if above means something to you.
 
![image](https://user-images.githubusercontent.com/65233253/104192824-5dbdb380-53ed-11eb-9d65-82cac7b504db.png)

**Comment by ImrozCinchy** [comment]
It worked when I kept the versions same to older one both in iframe and parent.
Thanks for the updates.

**Comment by davidjbradshaw** [comment]
This looks like a problem with your setup, rather than anything I can help
you with

**Comment by ImrozCinchy** [comment]
Yeah, it worked when I kept versions the same.
